apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: sonarqube-deployment
  name: sonarqube
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube  
    spec: 
      containers: 
        - 
          env: 
            - 
              name: SONARQUBE_JDBC_USERNAME
              value: "medium@medium"
            - 
              name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://medium.postgres.database.azure.com/sonar"
            - 
              name: SONARQUBE_JDBC_PASSWORD
              value: Raposa@2023$
          image: "sonarqube:latest"
          name: sonarqube-pod
          ports: 
            - 
              containerPort: 9000
              protocol: TCP
          resources: 
            limits: 
              cpu: 2000m
              memory: 2048Mi
            requests: 
              cpu: 500m
              memory: 1024Mi
          volumeMounts: 
            - 
              mountPath: /opt/sonarqube/data/
              name: sonar-data
            - 
              mountPath: /opt/sonarqube/extensions/
              name: sonar-extensions
      volumes: 
        - 
          name: sonar-data
          persistentVolumeClaim: 
            claimName: sonar-data
        - 
          name: sonar-extensions
          persistentVolumeClaim: 
            claimName: sonar-extensions
